# 不区分大小写

app:
  env: local
  debug: true 
  system: GoGoGo  # 项目系统名称
  host: http://localhost # 域名
  port: 8083 
  logDir:  # 日志存储目录，不填写则打印到终端
  key: 

# 数据库
db:
  driver: mysql
  host: 127.0.0.1 
  port: 3306
  user: root 
  password: 
  dbname: 
  tablePrefix: 

# JWT
token:
  key: HelloWord 
  expires: 7200 #过期时间s

# 提醒机器人
robot:
  api:
  key: #没设置可以不填写


